version: "3.8"

services:
  sat-auth-service:
    image: sat-auth-service:latest
    build: .
    container_name: sat-auth-service
    restart: unless-stopped
    networks:
      - proxy-net

networks:
 proxy-net:
    external: true

