version: "3.8"

services:
  sat-auth-service:
    image: sat-auth-service:latest
    build: .
    container_name: sat-auth-service
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default # <-- ¡IMPORTANTE! Usa el nombre de tu red aquí.

networks:
  nginx-proxy-manager_default: # <-- ¡IMPORTANTE! Y también aquí.
    external: true
