version: '3.8'
services:
  sat-auth:
    build: .
    container_name: sat-auth-service
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    restart: unless-stopped