# docker-compose.yml

version: '3.8'
services:
  sat-auth-service:
    build: .
    container_name: sat-auth-service
    ports:
      - "3000:3000"
    networks:
      - default   # <-- AÑADE ESTA LÍNEA
      - proxy-net
    environment:
      NODE_ENV: production
      SAT_AUTH_URL: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/Autenticacion/Autenticacion.svc"
      SAT_DOWNLOAD_URL: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc"
      SAT_VERIFY_URL: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/VerificaSolicitudDescargaService.svc"
      SAT_PACKAGE_DOWNLOAD_URL: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc"
    restart: unless-stopped

networks:
  proxy-net:
    external: true
